"use strict";
// src/lib/game-data.ts

import type { RapidApiGameData, RapidApiExternalLink } from "./rapidapi/types";
import type { DetailedIndieGameReport } from "@/schema";

const rapidApiKey = process.env.RAPIDAPI_KEY;

if (!rapidApiKey) {
  console.error("RAPIDAPI_KEY environment variable is not set.");
}

export async function fetchSteamDataFromApi(
  appId: string
): Promise<RapidApiGameData | null> {
  // Return type 'any' for now, can be refined
  if (!rapidApiKey) {
    console.error("RAPIDAPI_KEY not configured for Steam API call.");
    return null;
  }
  if (!appId || !/^[0-9]+$/.test(appId)) {
    console.error(`Invalid Steam App ID provided: ${appId}`);
    return null;
  }

  const url = `https://games-details.p.rapidapi.com/gameinfo/single_game/${appId}`;
  const options = {
    method: "GET",
    headers: {
      "x-rapidapi-key": rapidApiKey,
      "x-rapidapi-host": "games-details.p.rapidapi.com",
    },
  };

  console.log(`[Game Data] Fetching Steam data via API for App ID: ${appId}`);
  try {
    const response = await fetch(url, options);
    if (!response.ok) {
      const errorBody = await response
        .text()
        .catch(() => "Failed to read error body");
      console.error(`[Game Data] Steam API Error Body: ${errorBody}`);
      throw new Error(
        `[Game Data] RapidAPI (games-details) failed for App ID ${appId}: ${response.status} ${response.statusText}`
      );
    }
    const result = await response.json();
    // Check structure based on observed RapidAPI responses
    if (result?.status !== 200 || !result?.data) {
      // Handle cases where API returns 200 but data is missing or indicates failure
      if (result?.data?.error) {
        console.warn(
          `[Game Data] Steam API returned error for App ID ${appId}: ${result.data.error}`
        );
        return null; // Treat as failure if error field exists
      }
      // Handle specific known non-success indicators if any
      if (result?.data?.name === null && result?.data?.desc === null) {
        console.warn(
          `[Game Data] Steam API returned seemingly empty data for App ID ${appId}:`,
          result.data
        );
        // Consider if this is truly an error or just missing data
        // For now, let's treat it as potentially invalid data
        return null;
      }
      console.warn(
        `[Game Data] Steam API returned non-success status or unexpected data structure for App ID ${appId}:`,
        result
      );
      // Return null if data structure is not as expected
      return null;
    }
    console.log(
      `[Game Data] Successfully fetched Steam API data for App ID: ${appId}`
    );
    return result.data as RapidApiGameData; // Return the nested 'data' object
  } catch (error) {
    console.error(
      `[Game Data] Error fetching Steam data for App ID ${appId} via API:`,
      error
    );
    return null;
  }
}

export function createPartialReportFromSteamApi(
  steamApiData: RapidApiGameData
): Partial<DetailedIndieGameReport> {
  // Helper to safely access nested properties
  const get = (obj: any, path: string, defaultValue: any = null) =>
    path.split(".").reduce((acc, part) => acc?.[part], obj) ?? defaultValue;

  // Tags are needed later but audience appeal is generated by AI now
  const tags: string[] = get(steamApiData, "tags", []);

  const report: Partial<DetailedIndieGameReport> = {
    gameName: get(steamApiData, "name"),
    gameDescription: get(steamApiData, "desc"),
    developerName: get(steamApiData, "dev_details.developer_name.0"),
    publisherName: get(steamApiData, "dev_details.publisher.0"),
    releaseInfo: get(steamApiData, "release_date"),
    genresAndTags: tags, // Use the extracted tags variable
    relevantLinks: [],
    audienceAppeal: null, // Initialize as null, will be filled by AI later
    overallReportSummary: null,
    aiConfidenceAssessment: "Report generated from Steam API data only.",
    fundingInfo: null,
    teamMembers: null,
    developerBackground: null,
    publisherInfo: null,
    sourceSteamUrl: null,
    // steamAppId will be added later before saving
  };

  // Add direct links from Steam API data
  const linksToAdd: Array<{
    url: string | null;
    type: string;
    name: string | null;
  }> = [];

  const externalLinks: RapidApiExternalLink[] = get(
    steamApiData,
    "external_links",
    []
  );
  externalLinks.forEach((link) => {
    let type = "Other Link";
    const lowerCaseName = link.name.toLowerCase();
    const lowerCaseUrl = link.link.toLowerCase();

    if (lowerCaseName === "website" || lowerCaseUrl.includes("notion.site")) {
      type = "Official Website";
    } else if (lowerCaseName === "x" || lowerCaseUrl.includes("twitter.com")) {
      type = "Twitter Profile";
    } else if (
      lowerCaseName === "instagram" ||
      lowerCaseUrl.includes("instagram.com")
    ) {
      type = "Instagram";
    }

    linksToAdd.push({ url: link.link, type: type, name: link.name });
  });

  const screenshots: string[] = get(steamApiData, "media.screenshot", []);
  screenshots.forEach((url, index) => {
    linksToAdd.push({
      url: url,
      type: "Screenshot",
      name: `Screenshot ${index + 1}`,
    });
  });

  const videos: string[] = get(steamApiData, "media.videos", []);
  videos.forEach((url, index) => {
    linksToAdd.push({ url: url, type: "Video", name: `Video ${index + 1}` });
  });

  report.relevantLinks = linksToAdd;

  return report;
}

// Placeholder for future fetching logic
// export async function fetchReviewData(appId: string): Promise<any> {
//   // Implementation needed
//   console.log(`[Game Data] TODO: Fetch review data for App ID: ${appId}`);
//   return null;
// }

// export async function fetchPricingData(appId: string): Promise<any> {
//   // Implementation needed
//   console.log(`[Game Data] TODO: Fetch pricing data for App ID: ${appId}`);
//   return null;
// }

// Placeholder for the combined function
// export async function fetchAndProcessGameData(appId: string) {
//   const steamData = await fetchSteamDataFromApi(appId);
//   if (!steamData) return null;

//   const reviews = await fetchReviewData(appId);
//   const pricing = await fetchPricingData(appId);

//   const partialReport = createPartialReportFromSteamApi(steamData);

//   // TODO: Process reviews and pricing
//   // TODO: Add processed data to partialReport or a new structure
//   // TODO: Generate text for embedding using richer data

//   return {
//     processedReport: partialReport, // Or the new structure
//     rawSteamData: steamData,
//     // rawReviewData: reviews,
//     // rawPricingData: pricing,
//     // textForEmbedding: generatedText,
//   };
// }
